name: 'HAP Lock'
description: 'Integração ao HomeKit de Fechadura com Cartão NFC'
version: '0.0.9'
slug: 'hap_lock_homeassistant'
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  device_name: ''
  device_manufacturer: ''
  device_serial_number: ''

schema:
  device_name: str
  device_manufacturer: str
  device_serial_number: str
